// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1551615778);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1551615898);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1551683986);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1551680338);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1551680218);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1551615658);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1551356938);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1551616018);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1551356069);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{89ab1966-fa51-499a-aab9-1cbb891d0788}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1551308400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1551683964306");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1551685737306");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1551683965187");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1551687565187");
user_pref("browser.search.region", "AL");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1551683959");
user_pref("browser.slowStartup.averageTime", 8439);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190215001155");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1551356072440");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "8403657e838d4bbe93e62c1c10df3586");
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1551615778);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"602f2842-605a-4764-8880-8583b49af3b6\",\"screenshots@mozilla.org\":\"5d450f8d-3957-4d96-8cf1-f64ddedcbc4a\",\"webcompat-reporter@mozilla.org\":\"8882e2f2-870d-4d5e-99ec-c1ada981f534\",\"webcompat@mozilla.org\":\"a5b81400-b809-4188-a290-dc70e586606e\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1551616105);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.benchmark.vp9.fps", 207);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1551683993);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190215001155");
user_pref("media.gmp-manager.lastCheck", 1551683992);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1551356905);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "694b837d-6bc5-485f-a7b2-1b72f6cee31c");
user_pref("security.sandbox.plugin.tempDirSuffix", "b88e3590-dee0-49da-8814-59620134fc28");
user_pref("services.blocklist.addons.checked", 1551683962);
user_pref("services.blocklist.gfx.checked", 1551683962);
user_pref("services.blocklist.onecrl.checked", 1551683962);
user_pref("services.blocklist.pinning.checked", 1551683962);
user_pref("services.blocklist.plugins.checked", 1551683962);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1551491391898\"");
user_pref("services.settings.last_update_seconds", 1551683962);
user_pref("services.settings.main.language-dictionaries.last_check", 1551683962);
user_pref("services.settings.main.onboarding.last_check", 1551683962);
user_pref("services.settings.main.sites-classification.last_check", 1551683962);
user_pref("services.settings.main.tippytop.last_check", 1551683962);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1551356905);
user_pref("toolkit.startup.last_success", 1551683951);
user_pref("toolkit.telemetry.cachedClientID", "cbf7a26d-118e-492b-a56c-b47f25840013");
user_pref("toolkit.telemetry.previousBuildID", "20190215001155");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
